### ISSUE TITLE
Use default navbar?

### ISSUE THREAD

**Issue by peterdesmet** [inbo/watina#15]
https://github.com/inbo/watina/commit/eb4042463c0e02c98d92a403d805dd81c227c2cf cancels the use of the default navbar.  If the blue colour is to be kept, the navbar could just use:

```
navbar:
  type: inverse
```

Discussed with @florisvdh that it would be good to suggest `Functions` and `Tutorials` as titles in pkgdown repo.

**Comment by florisvdh** [comment]
@peterdesmet Hadley Wickham [argues](https://github.com/r-lib/pkgdown/issues/1105#issuecomment-525059631) that package documentation is not always (exclusively) about functions and tutorials.

It is clear that an easier way to manage some `navbar` titles (without taking over the `navbar` setup) would be nice, but he currently advises the customized approach.

However, having to maintain the complete navbar configuration (title entries etc.) each time that vignette titles change etc. is far from ideal in the long run. Therefore I have followed your initial advice, see commit 0c596f6.

I see two further possible approaches, in order to get better grip on website customization without impacting maintenance burden:

- regarding visual layout (colours etc.): providing extra site-style types ourselves, which we can then use as navbar's `type` parameter. E.g. agreeing on an INBO style; providing more styles to `pkgdown`.
- regarding the navigation bar titles: adapting `pkgdown` in order to set some titles explicitly in `_pkgdown.yml` without having to take over the whole navigation bar.

**Comment by peterdesmet** [comment]
Thanks! Yes, I would suggest to then do the first approach and create a minimal INBO css pkgdown theme (without the visual issues that git2rdata has). Maybe something for 2020?
